# -*- coding: utf-8 -*-
"""Chatbot_FAQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XoEeTmzyDzAqUP3pXZVBSUByXWfpFync
"""

!pip install -q gradio scikit-learn

import gradio as gr
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

faqs = {
    "questions": [
        "What products do you offer?",
        "What is the price range?",
        "Do you have products for dry skin?",
        "Do you have products for oily skin?",
        "What products help with acne?",
        "Are your products cruelty-free?",
        "Are your products vegan?",
        "What is the shelf life?",
        "How do I choose a moisturizer?",
        "What is a basic skincare routine?",
        "Do you offer products for sensitive skin?",
        "How often should I exfoliate?",
        "What is the difference between serum and moisturizer?",
        "Do you ship internationally?",
        "What is your return policy?",
        "Do you offer samples?",
        "Where can I buy your products?",
        "How do I contact customer service?",
        "What ingredients do you avoid?",
        "Can I use your products during pregnancy?"
    ],
    "answers": [
        "We offer cleansers, toners, serums, moisturizers, face masks, sunscreens, and eye creams.",
        "Our products range from $12 to $85, with options for every budget.",
        "Yes! Our Hydrating line includes moisturizers with hyaluronic acid and ceramides.",
        "Yes! Our Oil-Control range includes mattifying cleansers and oil-free moisturizers.",
        "Our Acne Control system with salicylic acid and tea tree oil helps treat breakouts.",
        "Yes, we are Leaping Bunny certified and never test on animals.",
        "Over 80% of our products are vegan. Look for the vegan logo on product pages.",
        "Products last 12-24 months unopened, 6-12 months after opening.",
        "Choose based on skin type: gel for oily, cream for dry, lotion for combination skin.",
        "Cleanse, tone, apply serum, moisturize, and use sunscreen in the morning.",
        "Yes! Our Sensitive Skin line is fragrance-free with soothing ingredients.",
        "Exfoliate 1-3 times per week based on your skin type.",
        "Serums have concentrated active ingredients, moisturizers hydrate and protect.",
        "Yes, we ship to over 50 countries worldwide.",
        "30-day return policy for unopened products, 14 days for opened products.",
        "Yes! We offer sample kits on our website and free samples with purchases.",
        "Available on our website, Sephora, Ulta, and authorized retailers.",
        "Email us at care@glowskin.com or call 1-800-GLOWSKIN.",
        "We avoid parabens, sulfates, phthalates, and synthetic fragrances.",
        "Most products are safe, but avoid retinol and high salicylic acid. Consult your doctor."
    ]
}

class SkincareBot:
    def __init__(self, questions, answers):
        self.questions = questions
        self.answers = answers
        self.vectorizer = TfidfVectorizer()
        self.question_vectors = self.vectorizer.fit_transform(questions)

    def get_answer(self, user_question):
        user_vector = self.vectorizer.transform([user_question.lower()])
        similarities = cosine_similarity(user_vector, self.question_vectors)
        best_idx = np.argmax(similarities)
        best_score = similarities[0][best_idx]

        if best_score > 0.2:
            return self.answers[best_idx]
        else:
            return "I'm sorry, I don't have information about that. Please ask about our products, ingredients, or skincare routines!"

bot = SkincareBot(faqs["questions"], faqs["answers"])

def chatbot_response(message, history):
    return bot.get_answer(message)

custom_css = """
.gradio-container {
    background: #C71585 !important;
}
#component-0 {
    max-width: 900px;
    margin: auto;
    padding: 20px;
    background: #DB7093;
    border-radius: 20px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.3);
}
h1, h2, h3, p, label, .gr-form {
    color: #FFB6C1 !important;
}
.message-wrap {
    border-radius: 15px !important;
}
.user {
    background: #FF69B4 !important;
    color: #FFB6C1 !important;
}
.bot {
    background: #C71585 !important;
    color: #FFB6C1 !important;
}
button {
    background: #FF69B4 !important;
    color: #FFB6C1 !important;
    border: none !important;
}
.chatbot {
    background: #DB7093 !important;
}
"""

demo = gr.ChatInterface(
    fn=chatbot_response,
    title="✨ GlowSkin - Skincare FAQ Chatbot",
    description="💆‍♀️ Welcome to GlowSkin! Ask me anything about our products, skincare routines, or ingredients.",
    examples=[
        "What products do you offer?",
        "Do you have products for dry skin?",
        "Are your products cruelty-free?",
        "What is a basic skincare routine?",
        "Do you offer samples?"
    ],
    css=custom_css,
    chatbot=gr.Chatbot(height=450, show_copy_button=True)
)

demo.launch(share=True)